In [1]:
import numpy as np 
import pandas as po
import matplotlib.pyplot as plt

In [2]:
from statsmodels.stats.contingency_tables import mcnemar

In [53]:
train_hist = {}
base_dir = 'results/final_plots/'

In [54]:
model='lstmfcn'
train_hist[model] = {}
with open(base_dir+model+ '/plots/predictions.npz', 'rb') as f:
    data = np.load(f)

    y_true = data['y_true']
    y_pred = data['y_pred']

train_hist[model]['y_true'] = np.argmax(y_true, axis = 1)
train_hist[model]['y_pred'] = np.argmax(y_pred, axis = 1)
#train_hist[model]['y_prob_true'] = y_predz[:, 1]

In [55]:
model='transformer'
train_hist[model] = {}
with open(base_dir+model+ '/plots/predictions.npz', 'rb') as f:
    data = np.load(f)

    y_true = data['y_true']
    y_pred = data['y_pred']

train_hist[model]['y_true'] = np.argmax(y_true, axis = 1)
train_hist[model]['y_pred'] = np.argmax(y_pred, axis = 1)
#train_hist[model]['y_prob_true'] = y_predz[:, 1]

In [56]:
train_hist['lstmfcn']['y_true']

array([0, 0, 1, ..., 0, 0, 0])

In [57]:
train_hist['lstmfcn']['y_pred']

array([0, 0, 0, ..., 0, 0, 0])

In [58]:
lstmfcn_correct = np.where(train_hist['lstmfcn']['y_true']==train_hist['lstmfcn']['y_pred'], 1, 0)
lstmfcn_correct

array([1, 1, 0, ..., 1, 1, 1])

In [59]:
model

'transformer'

In [60]:
cnn_correct = np.where(train_hist[model]['y_true']==train_hist[model]['y_pred'], 1, 0)
cnn_correct

array([1, 1, 0, ..., 1, 1, 1])

In [61]:
yy = np.where(np.logical_and(lstmfcn_correct==cnn_correct, lstmfcn_correct==1), 1, 0) # Equal and both correct
yy

array([1, 1, 0, ..., 1, 1, 1])

In [62]:
nn = np.where(np.logical_and(lstmfcn_correct==cnn_correct, lstmfcn_correct==0), 1, 0) # Equal and both wrong
nn

array([0, 0, 1, ..., 0, 0, 0])

In [63]:
yn = np.where(np.logical_and(lstmfcn_correct!=cnn_correct, lstmfcn_correct==1), 1, 0) # Different and lstmfcn is correct 
yn

array([0, 0, 0, ..., 0, 0, 0])

In [64]:
ny = np.where(np.logical_and(lstmfcn_correct!=cnn_correct, lstmfcn_correct==0), 1, 0) # Different and lstmfcn is wrong 
ny

array([0, 0, 0, ..., 0, 0, 0])

In [65]:
np.sum(yn)

42

In [66]:
np.sum(ny)

16

In [67]:
table = np.array([[np.sum(yy), np.sum(yn)], [np.sum(ny), np.sum(nn)]])
table

array([[4139,   42],
       [  16,  658]])

In [68]:
print(mcnemar(table, exact=False, correction=True)) # transformer

pvalue      0.0010283231106303406
statistic   10.775862068965518


In [36]:
print(mcnemar(table, exact=False, correction=True)) # resnet

pvalue      0.0
statistic   2487.1890809443507


In [19]:
print(mcnemar(table, exact=False, correction=True)) # fcn 

pvalue      0.0012114973654306278
statistic   10.472727272727273


In [61]:
print(mcnemar(table, exact=False, correction=True)) # cnn 

pvalue      8.296547354886757e-36
statistic   156.0401337792642


In [ ]:
# Reject Null hypothesis